language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/

before_install:
  - composer install --prefer-dist --no-progress --no-suggest
  - mkdir -p build/logs/

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff --ansi -v
  - vendor/bin/phan --no-progress-bar --color --allow-polyfill-parser
  - vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls -v

branches:
  only:
    - master
