language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer install --dev --prefer-source
  - mkdir -p build/logs

script:
  - phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v

branches:
  except:
    - /\//
