language: php

php:
  - 5.4.16
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - composer install --dev --prefer-source
  - mkdir -p build/logs

script:
  - phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v

branches:
  except:
    - /\//
